theme: jekyll-theme-minimal
title: Kelsey is the best.
description: xoxo
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Setup
    url: setup
  -title: Kelsey is the best.
    url: pza
  -title: Isoniazid Uptake
    url: niz

